### ISSUE TITLE
403 Forbidden error after authenticating and forwarding back to /verify

### ISSUE THREAD

**Issue by hiphigi** [cpancake/steam-login#17]
After logging in with Steam on `/authenticate`, there is a `403 Forbidden` error on the `/verify` page with the following output:

```
StatusCodeError: 403 - <html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>
    at new StatusCodeError (C:\Dev\Node\apps\my-app\node_modules\request-promise\lib\errors.js:26:15)
    at Request.RP$callback [as _callback] (C:\Dev\Node\apps\my-app\node_modules\request-promise\lib\rp.js:64:32)
    at Request.self.callback (C:\Dev\Node\apps\my-app\node_modules\request\request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Dev\Node\apps\my-app\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Dev\Node\apps\my-app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:275:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```

Here is the resulting URL after being forwarded back from Steam.

`http://localhost:8080/verify?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198213932720&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198213932720&openid.return_to=http%3A%2F%2Flocalhost%3A8080%2Fverify&openid.response_nonce=2018-05-13T21%3A56%3A57ZTpiACaxqXCuk4%2F7YTkETObZGb1g%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=tAz6V5Tzt7uQ9Wf4f4AhawmS40c%3D`

I've worked with Steam login on PHP but never Node, sorry if this is a novice mistake. I tried searching first but found nothing.

**Comment by ajzbc** [comment]
You need to start it with: `node [filename].js "[steam api key]"`

**Comment by BladeSe7en** [comment]
@ajzbc could you be a little more specific than start it with....
I am running into the same problem as hiphigi with the /verify route returning 403 forbidden.
Here is everything I have so far. What am I getting wrong with the /authenticate and /verify routes?
```const date = moment().format('lll');
var steam = require('steam-login');

app.use(require('express-session')({ resave: false, saveUninitialized: false, secret: 'a secret' }));
app.use(steam.middleware({
  realm: 'http://localhost:3000/',
  verify: 'http://localhost:3000/verify',
  apiKey: process.env.STEAM_ID
}));

app.get('/', function (req, res) {
  res.send(req.user == null ? 'not logged in' : 'hello ' + req.user.username).end();
});

app.get('/authenticate', steam.authenticate(), function (req, res) {
  res.redirect('/ForumMain');
});

app.get('/verify', steam.verify(), function (req, res) {
  fs.appendFile('log.csv', ('steam ID: ' + req.user._json.steamid) + '\t' + ('user name: ' + req.user._json.personaname) + '\t' + date + '\n', (err) => {
      if (err) throw err;
      res.sendFile(path.join(__dirname, '../src/components/ForumMain/ForumMain' ));  
  });
  steamUser = req.user._json;
});

app.get('/logout', steam.enforceLogin('/'), function (req, res) {
  req.logout();
  res.redirect('/');
});
