### ISSUE TITLE
Undefined result at verify

### ISSUE THREAD

**Issue by novikk** [cpancake/steam-login#2]
Hello,
I'm getting this error when there are many users trying to login at the same time.

```
/home/steam/web/apps/node_modules/steam-login/index.js:49
            fetchIdentifier(result.claimedIdentifier)
                                  ^
TypeError: Cannot read property 'claimedIdentifier' of undefined
    at /home/steam/web/apps/node_modules/steam-login/index.js:49:26
    at /home/steam/web/apps/node_modules/steam-login/node_modules/openid/openid.js:1068:12
    at /home/steam/web/apps/node_modules/steam-login/node_modules/openid/openid.js:1192:16
    at /home/steam/web/apps/node_modules/steam-login/node_modules/openid/openid.js:1310:16
    at done (/home/steam/web/apps/node_modules/steam-login/node_modules/openid/openid.js:318:9)
    at IncomingMessage.<anonymous> (/home/steam/web/apps/node_modules/steam-login/node_modules/openid/openid.js:322:32)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:891:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
```

Any idea on how to fix it?
Thanks

**Comment by dialupnoises** [comment]
I think this is actually a bug due to not returning after erroring when authentication fails. I've committed a possible fix, tell me if it works.

**Comment by novikk** [comment]
Thanks, that seems to work perfect!
